# Generated by Django 5.0.3 on 2024-03-16 10:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Device', '0002_alter_device_total_number'),
        ('Employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkout_at', models.DateTimeField()),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('condition_checkout', models.TextField()),
                ('condition_returned', models.TextField()),
                ('total_number', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Device.device')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employee.employee')),
            ],
        ),
    ]
