# Generated by Django 5.0.3 on 2024-03-16 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracking',
            name='condition_returned',
            field=models.TextField(blank=True, null=True),
        ),
    ]
